# Generated by Django 5.2.15 on 2026-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('corpus_type', models.CharField(max_length=16)),
                ('document_count', models.IntegerField(default=0)),
                ('bm25_index_path', models.CharField(blank=True, max_length=256)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
